baseURL = "https://mannyfin.github.io"
languageCode = "en-us"
title = "Emanuel Scoullos"
theme = "prologue"
publishdir = "mannyfin.github.io"

[params]
  name = "Emanuel Scoullos"
  description = "Chemical Engineer"
  copyright = "Emanuel Scoullos. 2018"

# [[params.social]]
#   medium = "twitter"
#   icon = "twitter"
#   link = "#"

# [[params.social]]
#   medium = "facebook"
#   icon = "facebook"
#   link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://www.github.com/mannyfin"

# [[params.social]]
#   medium = "dribbble"
#   icon = "dribbble"
#   link = "#"

# [[params.social]]
#   medium = "email"
#   icon = "envelope"
#   link = "#"

# Portfolio column one

# [[params.portfolio1]]
#   title = "Portfolio1img2"
#   alt = ""
#   source = "img/top_background.jpg"
#   url = "#"
#
# [[params.portfolio1]]
#   title = "Portfolio1img3"
#   alt = ""
#   source = "img/top_background.jpg"
#   url = "#"
#
# # Portfolio column two
#
# [[params.portfolio2]]
#   title = "Magna Nullam"
#   alt = ""
#   source = "img/top_background.jpg"
#   url = "#"
#
# [[params.portfolio2]]
#   title = "Natoque Vitae"
#   alt = ""
#   source = "img/classy.jpg"
#   url = "#"
#
# # Portfolio column 3
#
# [[params.portfolio3]]
#   title = "Dolor Penatibus"
#   alt = ""
#   source = "img/pic06.jpg"
#   url = "#"
#
# [[params.portfolio3]]
#   title = "Orci Convallis"
#   alt = ""
#   source = "img/photo.jpg"
#   url = "#"
